version: '3'

services:
  jenkins:
    image: erryial/jenkins
    container_name: jenkins_compose
    stdin_open: true
    restart: always
    tty: true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "50000:50000"
      - "8080:8080"
    environment:
      LICENSE_KEY: cfxk_3LG0M8zXAvgwdC7eiNT6_4FzTl
  registry:
    image: registry
    restart: always
    container_name: docker_registry
    ports:
      - "9999:5000"
